{% set name = "petsc4py" %}
{% set version = "3.16.0" %}
{% set sha256 = "4044accfdc2c80994e80e4e286478d1ba9ac358512d1b74c42e1327eadb0d802" %}
{% set build = 1 %}

{% set version_xy = version.rsplit('.', 1)[0] %}
{% if scalar == "real" %}
{% set build = build + 100 %}
{% endif %}

package:
  name: petsc4py
  version: {{ version }}

source:
  fn: petsc4py-{{ version }}.tar
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  script: PETSC_DIR=$PREFIX pip -v install --no-deps .
  skip: true  # [win]
  string: {{ scalar }}_h{{ PKG_HASH }}_{{ build }}
  track_features:
    - petsc4py_complex  # [scalar == "complex"]

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
    - {{ mpi }}
    - petsc {{ version_xy }}.* *{{ scalar }}*
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - {{ mpi }}
    - petsc * *{{ scalar }}*  # pinned by petsc run_exports
  run_constrained:
    - mpi4py >=3.0.1

about:
  home: https://bitbucket.org/petsc/petsc4py
  summary: Python bindings for PETSc
  license: BSD-2-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - dalcinl
    - minrk
    - davidbrochart
    - SylvainCorlay
